### ISSUE TITLE
Translation sheet 

### ISSUE THREAD

**Issue by jsecurity101** [hunters-forge/OSSEM#44]
As previously discussed offline, a translation sheet needs to be made for field names - logon_impersonation_level, SIDS, and more.

**Comment by Cyb3rWard0g** [comment]
Can you provide more details on this one @jsecurity101 ?

**Comment by jsecurity101** [comment]
Absolutely @Cyb3rWard0g, 
You, @neu5ron, and I talked in private about creating a translation sheet for things like `%%2500` to `logon_impersonation_level`. Standardizing the translations across the board for all events. Merge HELK and OSSEM a little easier that way.

**Comment by Cyb3rWard0g** [comment]
decided to just do it in a few mins from HELK pipeline configs. Document can grow as HELK parses more.
HELK pipe config: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/1545-winevent-security-conversions.conf
Doc: https://docs.google.com/spreadsheets/d/18hQ0f1Qr4zfK3alDjIMgoLMpX3XJZEbdMKIV7X8YHxI/edit?usp=sharing
